-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Nov 21, 2019 at 12:04 PM
-- Server version: 10.4.6-MariaDB
-- PHP Version: 7.3.8

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `db_gizisehat`
--

-- --------------------------------------------------------

--
-- Table structure for table `tb_admin`
--

CREATE TABLE `tb_admin` (
  `id_admin` int(11) NOT NULL,
  `username` varchar(100) NOT NULL,
  `password` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `tb_admin`
--

INSERT INTO `tb_admin` (`id_admin`, `username`, `password`) VALUES
(1, 'yuki', '3108');

-- --------------------------------------------------------

--
-- Table structure for table `tb_penyakit`
--

CREATE TABLE `tb_penyakit` (
  `id_penyakit` int(11) NOT NULL,
  `nama_penyakit` varchar(100) NOT NULL,
  `deskripsi_penyakit` text NOT NULL,
  `jenis_diet` text NOT NULL,
  `anjuran_makanan` text NOT NULL,
  `larangan_makanan` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `tb_penyakit`
--

INSERT INTO `tb_penyakit` (`id_penyakit`, `nama_penyakit`, `deskripsi_penyakit`, `jenis_diet`, `anjuran_makanan`, `larangan_makanan`) VALUES
(4, 'Asma', '<p>Merupakan penyakit paru-paru kronis yang menyebabkan penderita sulit bernapas. Hal ini disebabkan karena pengencangan dari otot sekitar saluran pernafasan, peradangan, rasa nyeri, pembengkakan, dan iritasi pada saluran nafas di paru-paru dengan kata lain Asma adalah suatu keadaan di mana terjadi penyempitan pada aliran nafas akibat dari rangsangan tertentu(pemicu) sehingga menyebabkan peradangan dan menyebabkan sulitnya bernafas dan berbunyi \"ngik\" setiap bernafas. Hal ini biasanya mengurangi kualitas hidup seorang penderita karena bisa menyebabkan gampang lelah dan gampang sakit</p>', '<p>Pada penderita asma terjadi gangguan pernafasan seperti batuk, sesak nafas, dan nafas tersengal-sengal. Oleh karena itu penderita asma harus jeli dalam memilih makanan agar asma tidak dan membuat semakin parah. Salah satunya dengan membatasi asupan makanan yang banyak mengandung sulfit dan bahan pengawet karena dapat memicu asma.</p>', '<p>&bull; Karbohidrat : Nasi, ubi, singkong, jagung, roti, mie, bihun, makaroni, pasta, talas, havermout, gamdum, tepung beras</p>\r\n<p>&bull; Protein : Telur, ikan daging, susu, daging ayam, ikan, kacang-kacangan.</p>\r\n<p>&bull; Lemak : Minyak jagung, minyak kacang tanah, minyak kelapa sawit, minyak kedelai, margarin, dan mentega rendah garam</p>\r\n<p>&bull; Sayuran : Semua jenis sayuran, seperti bayam, kangkung, kacang buncis, kacang panjang, wortel, tomat, labu siam, tauge. diperbolehkan</p>\r\n<p>&bull; Buah-buahan : Semua jenis buah-buahan, seperti pisang, pepaya, jeruk, mangga, nanas, jambu biji</p>', '<p>&bull; Kentang goreng, karena dalam kentang goreng terdapat kandungan sulfit. Sulfur merupakan kandungan yang sering dijadikan bahan pengawet dalam makanan yang dapat memicu asma manjadi kambuh</p>\r\n<p>&bull; Acar karena mengandung sulfit</p>\r\n<p>&bull; Daun bawang, pati, jagung, bawang putih</p>\r\n<p>&bull; Buah atau sayuran kering, seperti kismis, nanas, aprikot, cranberry, cery</p>\r\n<p>&bull; Minuman fermentasi, seperti bir, anggur, dan alkohol.</p>'),
(5, 'PPOK (Penyakit Paru Obstruktif Kronis)', '<p>Merupakan penyakit kronis saluran napas yang ditandai dengan hambatan aliran udara khususnya udara ekspirasi dan bersifat progresif lambat (semakin lama semakin memburuk), disebabkan oleh pajanan faktor risiko seperti merokok, polusi udara di dalam maupun di luar ruangan. Onset (awal terjadinya penyakit) biasanya pada usia pertengahan dan tidak hilang dengan pengobatan. Didefinisikan sebagai PPOK jika pernah mengalami sesak napas yang bertambah ketika beraktifitas dan/atau bertambah dengan meningkatnya usia disertai batuk berdahak atau pernah mengalami sesak napas disertai batuk berdahak</p>', '<p>Pada penderita PPOK ini terjadi peningkatan CO2 dalam arteri yang menyebabkan gagal napas, sehingga pemberian makanan sangat mempengaruhi kadar CO2 dalam darah. Pasien PPOK dianjurkan untuk asupan kalori diutamakan yang berasal dari lemak daripada kalori yang berasal dari sumber karbohidrat.</p>', '<p>&bull; Karbohidrat : nasi, beras merah, roti, mie, kentang, singkong, ubi, sagu</p>\r\n<p>&bull; Protein : Telur, ikan daging, susu, daging ayam, ikan, kacang-kacangan.</p>\r\n<p>&bull; Lemak : minyak kedelai, margarin dan mentega tanpa garam yang digunakan untuk menumis atau setup, santan encer Makanan diolah terutama dengan cara dipanggang, dikukus, distup, direbus, dibakar.</p>\r\n<p>&bull; Sayuran : Semua sayuran yaitu sayuran yang tidak mengandung gas dan tidak diawetkan , seperti bayam, kangkung, kacang panjang, labu siam, tomat, taoge, wortel.</p>\r\n<p>&bull; Buah-buahan : Semua buah-buahan segar yang dibuat jus atau di setup, seperti pisang, pepaya, jeruk, mangga, nanas, jambu biji</p>', '<p>&bull; Batasi sumber kalori yang berasal dari sumber karbohidrat kompleks, bisa digantikan dengan yang berasal dari sumber lemak, seperti daging-dagingan.</p>\r\n<p>&bull; Sayuran : Semua sayuran yang mengandung gas seperti: kol, kembang kol, lobak, sawi, nangka muda.</p>\r\n<p>&bull; Buah : Buah-buahan segar yang mengandung gas dan alkohol seperti: durian, dan nangka matang.</p>'),
(6, 'Kanker', '<p>Kanker atau tumor ganas adalah pertumbuhan sel/jaringan yang tidak terkendali, terus bertumbuh/bertambah, immortal (tidak dapat mati). Sel kanker dapat menyusup ke jaringan sekitar dan dapat membentuk anak sebar. Diagnosis kanker maupun jenis kanker ditegakkan berdasarkan hasil wawancara terhadap pertanyaan pernah didiagnosis menderita kanker oleh dokter.</p>', '<p>Gangguan gizi yang dapat timbul pada pasien kanker yaitu salah satunya disebabkan oleh kurangnya asupan makanan, sehingga tujuan diberikannya diet penyakit kanker guna mempertahankan status gizi yang optimal, dengan memberikan makanan yang seimbang sesuia dengan keadaan penyakit serta daya terima pasien.</p>', '<p>Bila pasien menderita anoreksia :</p>\r\n<p>&bull; Dianjurkan makanan yang disukai atau dapat diterima walaupun tidak lapar</p>\r\n<p>Bila ada perubahan pengecapan :</p>\r\n<p>&bull; Makanan atau minuman diberikan dengan suhu kamar atau sudah dingin</p>\r\n<p>&bull; Tambahkan bumbu dalam makanan untuk menambah rasa</p>\r\n<p>&bull; Minuman segar, seperti : sari buah atau jus</p>\r\n<p>Bila ada kesulitan mengunyah atau menelan :</p>\r\n<p>&bull; Minum menggunakan sedotan</p>\r\n<p>&bull; Bentuk makanan disaring atau cair</p>\r\n<p>Bila mulut kering :</p>\r\n<p>&bull; Bentuk makanan cair</p>\r\n<p>&bull; Kunyah permen karet atau hard candy</p>\r\n<p>&bull; Makanan atau minuman dalam suhu dingin</p>\r\n<p>Bila mual dan muntah :</p>\r\n<p>&bull; Beri makanan kering</p>\r\n<p>&bull; Minum dan makan perlahan-lahan</p>\r\n<p>&bull; Tidak tiduran setelah makan</p>', '<p>Bila pasien menderita anoreksia :</p>\r\n<p>&bull; Hindari minum sebelum makan karena memnuat perut terasa penuh</p>\r\n<p>Bila ada kesulitan mengunyah atau menelan :</p>\r\n<p>&bull; Hindari makanan terlalu asam atau manis</p>\r\n<p>Bila mual dan muntah :</p>\r\n<p>&bull; Hindari makanan yang berbau merangsang</p>\r\n<p>&bull; Hindari makanan dengan kemak tinggi</p>\r\n<p>&bull; Hindari makanan atau minuman terlalu manis</p>\r\n<p>&bull; Batasi cairan saat makan</p>'),
(7, 'Diabetes  Milletus', '<p>Merupakan penyakit metabolisme yang merupakan suatu kumpulan gejala yang timbul pada seseorang karena adanya peningkatan kadar glukosa darah di atas nilai normal. Penyakit ini disebabkan gangguan metabolisme glukosa akibat kekurangan insulin baik secara absolut maupun relatif. Ada 2 tipe diabetes melitus yaitu diabetes tipe I/diabetes juvenile yaitu diabetes yang umumnya didapat sejak masa kanak-kanak dan diabetes tipe II yaitu diabetes yang didapat setelah dewasa. Gejala diabetes antara lain: rasa haus yang berlebihan (polidipsi), sering kencing (poliuri) terutama malam hari, sering merasa lapar (poliphagi), berat badan yang turun dengan cepat, keluhan lemah, kesemutan pada tangan dan kaki, gatal-gatal, penglihatan jadi kabur, impotensi, luka sulit sembuh, keputihan, penyakit kulit akibat jamur di bawah lipatan kulit, dan pada ibu-ibu sering melahirkan bayi besar dengan berat badan &gt;4 kg. Didefinisikan sebagai DM jika pernah didiagnosis menderita kencing manis oleh dokter atau belum pernah didiagnosis menderita kencing manis oleh dokter tetapi dalam 1 bulan terakhir mengalami gejala: sering lapar dan sering haus dan sering buang air kecil &amp; jumlah banyak dan berat badan turun.</p>', '<p>Diet penyakit Diabetes Milletus diberikan untuk membantu pasien memperbaiki kebiasaan makan agar mempertahankan kadar glukosa darah dalam tubuh mendekati normal.</p>', '<p>&bull; Karbohidrat : nasi, roti, mie, kentang, singkong, ubi, sagu</p>\r\n<p>&bull; Protein rendah lemak: Ikan, ayam tanpa kulit, susu skim, tempe, tahu, kacang-kacangan.</p>\r\n<p>&bull; Lemak : Makanan diolah terutama dengan cara dipanggang, dikukus, distup, direbus, dibakar.</p>', '<p>&bull; Mengandung banyak gula sederhana : Gula pasir, gula jawa, sirup, jam, jeli, buah-buahan yang diawetkan dengan gula, susu kental manis, minuman botol ringan, eskrim, kue-kue manis, dodol, cake, tarcis.</p>\r\n<p>&bull; Mengandung banyak lemak : Cake, makanan cepat saji (fast food), goreng-gorengan.</p>\r\n<p>&bull; Mengandung banyak natrium : Ikan asin, telur asin, makanan yang diawetkan.</p>'),
(8, 'Hipertensi /tekanan darah tinggi', '<p>Merupakan suatu keadaan ketika tekanan darah di pembuluh darah meningkat secara kronis. Hal tersebut dapat terjadi karena jantung bekerja lebih keras memompa darah untuk memenuhi kebutuhan oksigen dan nutrisi tubuh. Jika dibiarkan, penyakit ini dapat mengganggu fungsi organ-organ lain,terutama organ-organ vital seperti jantung dan ginjal. Didefinisikan sebagai hipertensi jika pernah didiagnosis menderita hipertensi/penyakit tekanan darah tinggi oleh tenaga kesehatan (dokter/perawat/bidan)atau belum pernah didiagnosis menderita hipertensi tetapi saat diwawancara sedang minum obat medis untuk tekanan darah tinggi (minum obat sendiri). Kriteria hipertensi yang digunakan pada penetapan kasus merujuk pada kriteria diagnosis JNC VII 2003, yaitu hasil pengukuran tekanan darah sistolik &gt;= 140 mmHg atau tekanan darah diastolik &gt;= 90 mmHg.</p>', '<p>Diet yang diberikan yaitu diet rendah garam yang membantu menghilangkan retensi garam atau air dalam jaringan tubuh.</p>', '<p>&bull; Karbohidrat : Beras, kentang, singkong, terigu, tapioka, hunkwe, gula, makaroni, mie, bihun.</p>\r\n<p>&bull; Protein : Daging dan daging ikan (maksimal 100 g/hari), telur maksimal 1 btr/hari, semua kacang-kacangan yang dimasak tanpa garam dapur</p>\r\n<p>&bull; Sayuran : Semua sayuran yaitu sayuran yang tidak diawetkan dengan garam dapur dan natrium benzoat.</p>\r\n<p>&bull; Buah-buahan : Semua buah-buahan segar yang tidak diawetkan dengan garam dapur dan natrium benzoat.</p>\r\n<p>&bull; Lemak : Minyak goreng, margarin, dan mentega tanpa garam</p>\r\n<p>&bull; Bumbu : Semua bumbu-bumbu kering yang tidak mengandung garam dapur dan natrium. Penggunaan garam dapur sesuai dengan tingkatan jenis diet rendah garam.</p>', '<p>&bull; Karbohidrat : Roti, biskuit, kue-kue yang dimasak dengan garam dapur atau baking powder dan soda.</p>\r\n<p>&bull; Protein : Otak, ginjal, lidah, sarden, daging, ikan, susu, telur yang diawetkan dengan garam dapur, daging asap, ham, bacon, dendeng, abon, keju, ikan asin, ikan kaleng, kornet, ebi, udang kering, telur asin, telur pindang, keju, kacang tanah yang dimasak dengan garam dapur.</p>\r\n<p>&bull; Sayuran : Sayuran yang dimasak dan diawetkan dengan garam dapur dan natrium. Seperti sayuran dalem kaleng, asinan, acar, sawi asin.</p>\r\n<p>&bull; Buah-buahan : Buah-buahan yang diawetkan, seperti buah-buahan dalam kaleng</p>\r\n<p>&bull; Lemak : Margarin dan mentega biasa</p>\r\n<p>&bull; Bumbu : Baking powder, soda kue, vetsin, bumbu yang mengandug garam dapur seperti: kecap, terasi, maggi, tomato ketchup, petis, dan tauco.</p>'),
(9, 'Penyakit jantung', '<p>&bull; Penyakit jantung koroner adalah gangguan fungsi jantung akibat otot jantung kekurangan darah karena adanya penyempitan pembuluh darah koroner. Secara klinis, ditandai dengan nyeri dada atau terasa tidak nyaman di dada atau dada terasa tertekan berat ketika sedang mendaki/kerja berat ataupun berjalan terburu-buru pada saat berjalan di jalan datar atau berjalan jauh.</p>\r\n<p>&bull; Gagal Jantung/Payah Jantung (fungsi jantung lemah) adalah ketidakmampuan jantung memompa darah yang cukup ke seluruh tubuh yang ditandai dengan sesak nafas pada saat beraktifitas dan/atau saat tidur terlentang tanpa bantal, dan/atau tungkai bawah membengkak.</p>', '<p>Diet penyakit jantung ini diberikan kepada penderita dengan memberikan makanan secukupnya sesuai kebutuhan dan menghindari makanan dengan kadar lemak tinggi, serta mencegah atau menghilangkan penimbunan garam atau air.</p>', '<p>&bull; Karbohidrat : Beras, roti, mie, kentang, makaroni, biskuit,nteoung beras/terigu/sagu, kentang, gula pasir, gula merah, madu, sirup.</p>\r\n<p>&bull; Protein : Daging sapi dan daginga ayam dengan lemak rendah, ikan, telur, susu rendah lemak, kacang-kacangan kering seperti: kacang kedelai , tahu, tempe.</p>\r\n<p>&bull; Sayuran : Sayuran yang tidak mengandung gas seperti : bayam, kangkung, kacang buncis, kacang panjang, wortel, tomat, labu siam, tauge.</p>\r\n<p>&bull; Buah : Semua buah-buahan segar seperti: pisang, pepaya, jeruk, apel, melon, semangka, sawo.</p>\r\n<p>&bull; Lemak : Minyak jagung, minyak kedelai, margarin mentega dalam jumlah terbatas dan tidak untuk menggoreng tetapi untuk menumis, kelapa atau santan encer dalam jumlah terbatas.</p>\r\n<p>&bull; Minuman : Teh encer, coklat, sirup</p>\r\n<p>&bull; Semua bumbu selain bumbu yang tajam dan merangsang dalam jumlah terbatas.</p>', '<p>&bull; Karbohidrat : Makanan yang mengandung gas atau alkohol seoerti : ubi, singkong, tape singkong,, dan tape ketan.</p>\r\n<p>&bull; Protein : Daging sapi dan daging ayam yang berlemak, gajih, sosis, ham, hati, limpa, babat, otak, kepiting, kerang-kerangan, keju, dan susu full cream, kacang-kacangan yang mengandung lemak cukup tinggi seperti kacang tanah, kacang mete, kacang bogor.</p>\r\n<p>&bull; Sayuran : Semua sayuran yang mengandung gas seperti: kol, kembang kol, lobak, sawi, nangka muda.</p>\r\n<p>&bull; Buah : Buah-buahan segar yang mengandung gas dan alkohol seperti: durian, dan nangka matang.</p>\r\n<p>&bull; Lemak : Minyak kelapa dan minyak kelapa sawit, santan kental.</p>\r\n<p>&bull; Minuman : Teh/kopi kental, miuman yang mengandung soda dan alkohol, seperti bir dan wiski.</p>\r\n<p>&bull; Bumbu : Cabe, cabe rawit, dan bumbu-bumbu lain yang tajam dan merangsang</p>'),
(10, 'Stroke', '<p>Merupakan penyakit pada otak berupa gangguan fungsi syaraf lokal dan/atau global, munculnya mendadak, progresif, dan cepat. Gangguan fungsi syaraf pada stroke disebabkan oleh gangguan peredaran darah otak non traumatik. Gangguan syaraf tersebut menimbulkan gejala antara lain: kelumpuhan wajah atau anggota badan, bicara tidak lancar, bicara tidak jelas (pelo), mungkin perubahan kesadaran, gangguan penglihatan, dan lain-lain.</p>', '<p>Diet penyakit stroke ini diberikan pada penderita untuk memperbaiki keadaan makannya, seperti disfagia (kesulitan menelan), serta mempertahankan keseimbangan cairan dan lektrolit dengan membatasi penggunaan garam</p>', '<p>&bull; Karbohidrat : Beras, kentang, ubi, singkong, terigu, hunkwe, tapioka, sagu, gula, madu, serta produk olahan yang dibuat tanpa garam dapur dan soda/ baking powder seperti: makaroni, mie, bihun, roti, biskuit, kue kering.</p>\r\n<p>&bull; Protein Daging sapi dan ayam tampa lemak, ikan telur ayam, susu skim, susu full cream dalam jumlah terbatas, semua kacang-kacangan</p>\r\n<p>&bull; Lemak : Minyak jagung, minyak kedelai, margarin dan mentega tanpa garam yang digunakan untuk menumis atau setup, santan encer</p>\r\n<p>&bull; Sayuran : Sayuran berserat sedang yang dimasak, seperti: bayam, kangkung, kacang panjang, labu siam, tomat, taoge, wortel.</p>\r\n<p>&bull; Buah-buahan : Buah segar, dibuat jus atau di setup, seperti pisang, pepaya, jeruk, mangga, nanas, jambu biji</p>\r\n<p>&bull; Minuman : Teh, kopi, coklat dalam jumlah terbatas dan encer, susu skim dan sirup.</p>\r\n<p>&bull; Bumbu-bumbu : Bumbu-bumbu yang tidak tajam, seperti garam (terbatas), gula, bawang merah, bawang putih, jahe, laos, asem, kayu manis, dan pala.</p>', '<p>&bull; Karbohidrat : Produk olahan yang dibuat dengan garam dapur, soda/baking powder, kue-kue yang terlalu manis dan gurih.</p>\r\n<p>&bull; Protein : Daging sapi dan daging ayam berlemak, jerohan, otak, hati, ikan banyak duri, susu full cream, keju, eskrim, produk olahan protein hewani yang diawetkan seperti: daging asap, ham, bacon, dendeng, kornet, produk kacang-kacangan yang diawetkan dengan garam natrium atau digoreng.</p>\r\n<p>&bull; Lemak : Minyak kelapa, minyak kelapa sawit, margarin dan mentega biasa, santan kental, krim,produk gorengan.</p>\r\n<p>&bull; Sayuran : Sayuran yang menibulkan gas, seperti : sawi, kol, kembang kol, lobak. Sayuran berserat tinggi seperti: daun singkong, daun katuk, daun melinjo, pare, sayuran mentah.</p>\r\n<p>&bull; Buah-buahan : Buah yang menimbulkan gas, seperti nangka, durian, buah yang diawetkan dengan natrium, seperti buah kaleng dan asinan.</p>\r\n<p>&bull; Teh, kopi, dan coklat yang kental, minuman bersoda dan alkohol.</p>\r\n<p>&bull; Bumbu-bumbu : Bumbu yang tajam, seperti cabe, merica, dan cuka, yang mengandung bahan pengawet garam natrium, seperti kecap, maggi, terasi, petis, vetsin, soda, dan baking powder.</p>'),
(11, 'Ginjal', '<p>Merupakan kelainan yang mengenai organ ginjal yang timbul akibat berbagai faktor, misalnya infeksi, tumor, kelainan bawaan, penyakit metabolik atau degeneratif, dan lain-lain. Kelainan tersebut dapat mempengaruhi struktur dan fungsi ginjal dengan tingkat keparahan yang berbeda-beda. Pasien mungkin merasa nyeri, mengalami gangguan berkemih, dan lain-lain. Terkadang pasien penyakit ginjal tidak merasakan gejala sama sekali. Pada keadaan terburuk, pasien dapat terancam nyawanya jika tidak menjalani hemodialisis (cuci darah) berkala atau transplantasi ginjal untuk menggantikan organ ginjalnya yang telah rusak parah.</p>', '<p>Diet penyakit ginjal ini diberikan pada pasien dengan mambatasi asupan protein dalam makanannya tanpa memberatkan fungsi ginjal dan menjaga keseimbangan cairan dan elektrolit, karena penurunan fungsi ginjal secara mendadak yang terjadi penurunan pada Glomeruro Filtration Rate (GFR) sehingga terganggunya kemampuan ginjal untuk mengeluarkan produk-produk sisa metabolisme</p>', '<p>&bull; Karbohidrat : nasi, bihun, jagung, kentang, makaroni, mie, tepung-tepungan, singkong, ubi, selai, madu, permen</p>\r\n<p>&bull; Protein : Telur, daging, ikan, ayam, susu</p>\r\n<p>&bull; Lemak : Minyak jagung, minyak kacang tanah, minyak kelapa sawit, minyak kedelai, margarin, dan mentega rendah garam</p>\r\n<p>&bull; Sayuran dan buah : Semua sayuran dan buah yang mengandung kalium rendah, seperti apel, jeruk, sawo, anggur, tomat, wortel</p>', '<p>&bull; Protein : Kacang-kacangan dan hasil olahannya, seperti tmpe dan tahu.</p>\r\n<p>&bull; Lemak : Kelapa, santan, minyak kelapa, margarin, mentega biasa dan lemak hewan.</p>\r\n<p>&bull; Sayuran dan buah: Sayuran dan buah tinggi kalium, seperti pisang, bayam.</p>'),
(12, 'Penyakit sendi (gout arthritis)', '<p>Merupakan suatu penyakit inflamasi sistemik kronik pada sendi-sendi tubuh. Gejala klinik penyakit sendi/ rematik berupa gangguan nyeri pada persendian yang disertai kekakuan, merah, dan pembengkakan yang bukan disebabkan karena benturan/kecelakaan dan berlangsung kronis. Gangguan terutama muncul pada waktu pagi hari.</p>', '<p>Diet gout atthritis atau asam urat ini untuk menurunkan kadar asam urat dalam darah dan urin, yang disebabkan oleh metabolisme abnormal purin yang ditandai dengan meningkatnya kadar asam urat dalam darah yang menyebabkan peradangan sendi.</p>', '<p>&bull; Karbohidrat : Nasi, ubi, singkong, jagung, roti, mie, bihun, makaroni, pasta, talas, havermout, gamdum, tepung beras, kentang &bull; Protein : Susu, keju, telur, &bull; Lemak : Minyak jagung, minyak kedelai, margarin dan mentega tanpa garam yang digunakan untuk menumis atau setup, santan &bull; Sayuran : Wortel, labu siam, kacang panjang, terong, pare, onyong, ketimun, labu air, selada air, tomat, lobak. &bull; Buah-buahan: Semua macam buah-buahan &bull; Minuman : Semua macam minuman yang tidak beralkohol. &bull; Bumbu-bumbu: Semua macam bumbu secukupnya.</p>', '<p>&bull; Protein : Daging, ayam, ikan tongkol, tenggiri, bawal, bandeng, kerang, udang dibatasi maksimum 500 gram/hari, tempe, tahu maksimum 50 gram/hari, kacang-kacangan, seperti kacang tanah, kacang kedelai paling banyak 25 gram/hari. &bull; Lemak : Santan kental, makanan yang berlemak.</p>\r\n<p>&bull; Hindari yang mengandung kadar purin antara 150-800 mg/100 gram bahan makanan, seperti: hati, ginjal, jantung, limpa, otak, ham , sosis, babat, usus, paru, sarden, kaldu daging, bebek, burung, angsa, remis, ragi</p>\r\n<p>&bull; Sayuran : Bayam, buncis, daun/biji melinjo, kapri, kacang polong, kembang kol, asparagus, kangkung dan jamur maksimum 100 gram/hari.</p>\r\n<p>&bull; Minuman : Teh kental, kopi kental, minuman yang mengandung soda dan alkohol : soft drink, arak, ciu, bir.</p>');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `tb_admin`
--
ALTER TABLE `tb_admin`
  ADD PRIMARY KEY (`id_admin`);

--
-- Indexes for table `tb_penyakit`
--
ALTER TABLE `tb_penyakit`
  ADD PRIMARY KEY (`id_penyakit`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `tb_admin`
--
ALTER TABLE `tb_admin`
  MODIFY `id_admin` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `tb_penyakit`
--
ALTER TABLE `tb_penyakit`
  MODIFY `id_penyakit` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
